services:
  - type: web
    name: todo-backend
    env: python
    region: oregon
    plan: free
    rootDir: Backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: todo-db
          property: connectionString

databases:
  - name: todo-db
    databaseName: todo_db
    user: todo_user
    plan: free
